export type AuthResponse = { access_token: string; token_type: string };
export type Account = {
  id: number; name: string; email: string; telegram_linked: boolean; owner?: boolean;
  payment_method_saved?: boolean; subscription_expires_at: string | null; auto_renew: boolean;
  subscription_plan?: string; legal_accepted?: boolean; trial_active?: boolean; trial_days?: number; credit_balance?: number;
};
export type ChatItem = { id: string; role: "user" | "assistant"; text: string; createdAt: number; mediaUrl?: string; mediaUrls?: { url: string; mime: string; name: string }[]; mediaMime?: string; filename?: string; artifactId?: string; audioUrl?: string; audioMime?: string; audioAutoplay?: boolean; feedback?: string; actionNotice?: string; streaming?: boolean };
export type MemorySection = { category: string; title: string; items: { label: string; value: string }[] };
export type MemoryAudit = { category: string; key: string; confirmed: boolean; first_seen?: string; last_seen?: string; replacements: number };
export type MemoryResponse = { sections: MemorySection[]; permanent?: boolean; description?: string; audit?: MemoryAudit[] };
export type Reminder = { id: number; text: string; kind?: string; remind_at: string };
export type AlterNotification = { id: string; title: string; body: string; kind: string; route: string; data?: Record<string, unknown>; read: boolean; created_at: string | null };
export type CreditPack = { id: string; name: string; price: string; credits: number };
export type Subscription = { active: boolean; trial_active?: boolean; trial_days?: number; plan: string; plans: { id: string; name: string; price: string; credits: number }[]; credit_packs?: CreditPack[]; credit_balance?: number; price_rub: string; days: number; expires_at: string | null; auto_renew: boolean };
export type Agent = { status?: string; goal?: string; horizon_minutes?: number; tasks?: { id: string; title: string; status: string; depends_on?: string[]; result?: string }[]; current_task?: string; completed_steps?: number; total_steps?: number } | null;
export type Workflow = Record<string, unknown> | null;
export type MediaJob = { id: string; kind: "image" | "video"; status: "queued" | "running" | "completed" | "failed" | "cancelled"; progress: number; filename?: string; media_type?: string; data_base64?: string; error?: string };
export type MyDay = { date: string; focus: { kind: string; title: string; detail: string; at: string | null; priority: string; loop_index?: number }[]; next_step: { title: string; prompt: string }; counts: { reminders: number; open_loops: number; goals: number }; memory_permanent: boolean };
export type Scenario = { id: string; title: string; prompt: string; mode: string };
export type DiagnosticsQuality = { counters: Record<string, number>; latency: Record<string, { count: number; p50_ms: number; p95_ms: number; p99_ms: number; last_ms: number }>; history?: { created_at: string | null; counters: Record<string, number>; latency: DiagnosticsQuality["latency"] }[]; payments?: { status: string; amount_rub: string; created_at: string | null; paid_at: string | null }[]; tool_success: number; tool_empty: number; tool_failures: number; quality_warnings: number; model_reliability: { success: number; failures: number; fallback_rate: number }; configuration?: Record<string, unknown> };
export type ApiErrorShape = { detail?: string; message?: string; error?: string };
